[tool.poetry]
name = "alternativa-ejercicios-"
version = "0.1.0"
description = ""
authors = ["Barroso03 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
switcher = "^0.1.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
